# docker-compose.yml
version: "3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - PGHOST=postgres
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_puma_core
      - PGPORT=5431
    volumes:
      - ./src:/usr/src/app/src:Z
    # depends_on:
    #   - postgres
    command: sh -c "npm run dev"
  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     POSTGRES_PASSWORD: local_pass
  #     POSTGRES_USER: local_user
  #     POSTGRES_DB: local_puma_core
  #   ports:
  #     - "5431:5431"
  #   restart: unless-stopped
networks:
  default:
    external:
      name: pumacore_puma_core