# docker-compose.yml
version: "3"
services:
  merchant_server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - API_URL=core_server
      - MERCHANT_URL=http://merchant_server:3000
      - PGHOST=postgres_merchant
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_merchant_server
      - PGPORT=5432
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - ETH_NETWORK=3
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ../merchant.sdk:/usr/src/app/node_modules/pumapay_merchant_sdk
    depends_on:
      - postgres_merchant
    networks:
      - pumapay_merchant_sdk
    command: sh -c "npm run dev"

  postgres_merchant:
    image: postgres:9.6
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: local_merchant_server
    ports:
      - "5431:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - pumapay_merchant_sdk
    restart: unless-stopped

  redis:
    image: redis:5.0-rc-alpine
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    hostname: redis
    networks:
      - pumapay_merchant_sdk
    volumes:
      - redis-data:/data
    
networks:
  pumapay_merchant_sdk:
    external:
      name: pumacore_puma_core
volumes:
  redis-data: