# docker-compose.yml
version: "3"
services:
  merchant_server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - CORE_API_URL=http://core_server:8081
      - MERCHANT_URL=http://merchant_server:3000
      - PGHOST=postgres_merchant
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_merchant_server
      - PGPORT=5432
      - REDIS_PORT=6379
      - REDIS_TOKEN=123456789
      - REDIS_HOST=merchant_redis
      - ETH_NETWORK=3
      - KEY_DB_HOST=merchant_db
      - KEY_DB_USER=db_service
      - KEY_DB_PASS=db_pass
      - KEY_DB=keys
      - KEY_DB_PORT=3306
      - MNEMONIC_ID=mnemonic_phrase
      - SENDGRID_API_KEY=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
      - BALANCE_MONITOR_INTERVAL=21600000
      - BALANCE_CHECK_THRESHOLD=0.1
      - BALANCE_CHECK_EMAIL=developers@pumapay.io
      - BALANCE_CHECK_EMAIL_PROD=developers@pumapay.io
      - CORE_API_KEY=439b42e67a947be164e8ba4dfd6cc24ff0915154e33d48c8924088d39a35ff7413a32849d88cb96ecead49a58329bd8a69c38f0374305c3699b7835491693a0c
      - MERCHANT_ID=4a17335e-bf18-11e8-a355-111111fb1459
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_REGION=0
      - AWS_KEY_ID=0
      - ENCRYPTION_MODULE=none
      - TOKEN_ADDRESS=0x11c1e537801cc1c37ad6e1b7d0bdc0e00fcc6dc1
      - PULL_PAYMENT_TOPIC_REGISTER=0x428ab8c1610a031128b670bb25673444ab666a8ffc071f4d10f9a4d4111cc4b9
      - PULL_PAYMENT_TOPIC_CANCEL=0x172a33cda438041634fc514b27425640f7d77fd7bd679f07f1931d454b08fa78
      - PULL_PAYMENT_TOPIC_EXECUTE=0x13492443fb72a9a7d56cc1aa2e262bcf2442d4b084def464b7934b3485114e59
      - PUMAPAY_PULL_PAYMENT_ADDRESS=0xd996F8A7298D822eEb71868c93ECEB106401A5fe
    volumes:
      - ./src:/usr/src/app/src
      - ./contracts:/usr/src/app/contracts
      - ./src/swagger.yml:/usr/src/app/src/swagger.yml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - postgres_merchant
    networks:
      - pumapay_merchant_sdk
    command: sh -c "npm run dev"

  postgres_merchant:
    image: postgres:9.6
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: local_merchant_server
    ports:
      - "5431:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - pumapay_merchant_sdk
    restart: unless-stopped

  merchant_redis:
    image: redis:5.0-rc-alpine
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - "6379:6379"
    command: sh -c "redis-server"
    hostname: redis
    networks:
      - pumapay_merchant_sdk
    volumes:
      - redis-data:/data
    
  merchant_db: 
    image: mysql:5.7.13
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
      MYSQL_DATABASE: keys
      MYSQL_USER: db_service
      MYSQL_PASSWORD: db_pass
    volumes: 
      - ./account-db/init/init-tables.sql:/docker-entrypoint-initdb.d/01-init-tables.sql
      - ./account-db/stored-procedures/add_account.sql:/docker-entrypoint-initdb.d/21-add-account.sql
      - ./account-db/stored-procedures/get_account.sql:/docker-entrypoint-initdb.d/23-get-account.sql
      - ./account-db/stored-procedures/add_mnemonic.sql:/docker-entrypoint-initdb.d/30-add-mnemonic.sql
      - ./account-db/stored-procedures/get_mnemonic.sql:/docker-entrypoint-initdb.d/31-get-mnemonic.sql
      - ./account-db/stored-procedures/get_private_key_from_address.sql:/docker-entrypoint-initdb.d/32-get-private-key-from-address.sql
      - ./account-db/init/add_data.sql:/docker-entrypoint-initdb.d/34-add_data.sql
    ports:
      - "3305:3306"
    networks: 
      - pumapay_merchant_sdk
    
networks:
  pumapay_merchant_sdk:
    external:
      name: pumacore_puma_core
volumes:
  redis-data: