# docker-compose.yml
version: "3"
services:
  merchant_server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - API_URL=core_server
      - PGHOST=postgres_merchant
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_merchant_server
      - PGPORT=5431
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./node_modules/puma_sdk_core:/usr/src/app/node_modules/puma_sdk_core
    depends_on:
      - postgres_merchant
    command: sh -c "npm run dev"
    networks:
      - pumacore_puma_core

  postgres_merchant:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: local_pass
      POSTGRES_USER: local_user
      POSTGRES_DB: local_merchant_server
    ports:
      - "5431:5432"
    networks:
      - pumacore_puma_core
    restart: unless-stopped
    
networks:
  pumacore_puma_core:
    external:
      name: pumacore_puma_core