# docker-compose.yml
version: "3"
services:
  merchant_server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - API_URL=core_server
      - PGHOST=postgres_merchant
      - PGUSER=local_user
      - PGPASSWORD=local_pass
      - PGDATABASE=local_merchant_server
      - PGPORT=5432
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ../merchant.sdk:/usr/src/app/node_modules/pumapay_merchant_sdk
    depends_on:
      - postgres_merchant
    networks:
      - pumapay_merchant_sdk
    command: sh -c "npm run dev"

  postgres_merchant:
    image: postgres:9.6
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: local_merchant_server
    ports:
      - "5431:5432"
    volumes:
      - ./db/init-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:Z
      - ./db/create-function-insert-payment.sql:/docker-entrypoint-initdb.d/2-create-function-insert-payment.sql:Z
      - ./db/create-function-update-payment.sql:/docker-entrypoint-initdb.d/3-create-function-update-payment.sql:Z
      - ./db/create-function-delete-payment.sql:/docker-entrypoint-initdb.d/4-create-function-delete-payment.sql:Z
      - ./db/create-function-get-single-payment-details.sql:/docker-entrypoint-initdb.d/5-create-function-get-single-payment-details.sql:Z
      - ./db/create-function-get-all-payments-details.sql:/docker-entrypoint-initdb.d/6-create-function-get-all-payments-details.sql:Z
    networks:
      - pumapay_merchant_sdk
    restart: unless-stopped
    
networks:
  pumapay_merchant_sdk:
    external:
      name: pumacore_puma_core